<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getJobsByUser(User $user)
    {
        return $this->createQueryBuilder('job')
        ->andWhere('job.createdBy = :user')
        ->setParameter('user', $user)
        ->orderBy('job.title', 'DESC')
        ->getQuery()
        ->execute();
    }
}
