<?php

namespace AppBundle\Repository;

/**
 * UserJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserJobRepository extends \Doctrine\ORM\EntityRepository
{

}
