phapp:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

admin_area:
   resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
   prefix: /admin

_sonata_admin:
   resource: .
   type: sonata_admin
   prefix: /admin